workbook:
  title: 2021학년도 대학수학능력시험 물리학 I
  year: 2020
  month: 11
  price: 0
  detail: ""
  image: ./표지_경로.jpg
  publisher: 한국교육과정평가원
  category: 수능 모의고사
  subject: 물리
  grade: 12

sections:
  - index: 1
    title: 2021학년도 대학수학능력시험 물리학 I
    detail: ""
    cutoff:
      - name: "1등급"
        score: 89
      - name: "2등급"
        score: 83
    views:
      - form: 0
        problems:
          - icon_index: 1
            icon_name: "1"
            type: 1
            answer: "3"
            score: 2
            content: "./fdfd0.png"
      - form: 0
        problems:
          - icon_index: 2
            icon_name: "2"
            type: 1
            answer: "2"
            score: 3
            content: "./fdfd1.png"
      - form: 0
        problems:
          - icon_index: 3
            icon_name: "3"
            type: 1
            answer: "5"
            scpre: 2
            content: "./fdfd2.png"
