workbook:
  title: 2021학년도 대학수학능력시험 3월 모의평가 국어(A)영역
  year: 2020
  month: 3
  price: 0
  detail: ""
  bookcover: img_1.png
  publisher: 한국교육과정평가원
  category: 수능모의고사
  subject: 국어(A)
  grade: 12

sections:
  title: 2021학년도 대학수학능력시험 3월 모의평가 국어(A)영역
  - index: 1
    detail: ""
    sectioncover: img_1.png
    cutoff:
    views:
      - form: 1
        material: img_0.png
        problems:
          - icon_index: 1
            icon_name: "1"
            type: 5
            answer: "3"
            score: 3
            content: img_1.png
            explanation: hsj_0.png
          - icon_index: 2
            icon_name: "2"
            type: 5
            answer: "3"
            score: 3
            content: img_2.png
            explanation: hsj_1.png
          - icon_index: 3
            icon_name: "3"
            type: 5
            answer: "3"
            score: 3
            content: img_3.png
            explanation: hsj_2.png
          - icon_index: 4
            icon_name: "4"
            type: 5
            answer: "3"
            score: 3
            content: img_4.png
            explanation: hsj_3.png
      - form: 1
        material: img_5.png
        problems:
          - icon_index: 5
            icon_name: "5"
            type: 5
            answer: "3"
            score: 3
            content: img_6.png
            explanation: hsj_4.png
          - icon_index: 6
            icon_name: "6"
            type: 5
            answer: "3"
            score: 3
            content: img_7.png
            explanation: hsj_5.png
          - icon_index: 7
            icon_name: "7"
            type: 5
            answer: "3"
            score: 3
            content: img_8.png
            explanation: hsj_6.png
          - icon_index: 8
            icon_name: "8"
            type: 5
            answer: "3"
            score: 3
            content: img_9.png
            explanation: hsj_7.png
          - icon_index: 9
            icon_name: "9"
            type: 5
            answer: "3"
            score: 3
            content: img_10.png
            explanation: hsj_8.png
          - icon_index: 10
            icon_name: "10"
            type: 5
            answer: "3"
            score: 3
            content: img_11.png
            explanation: hsj_9.png
