version: '3'

volumes:
  mysql_data: {}

services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/data:/data:Z
      - /home/ubuntu/tmp:/tmp:Z
    container_name: semomun-backend
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_PASSWORD}"
      - MYSQL_DATABASE="${DB_DATABASE}"
    volumes:
      - mysql_data:/var/lib/mysql:Z
    container_name: semomun-mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis:Z
    container_name: semomun-redis
