# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: [self-hosted, test]

    steps:
    - uses: actions/checkout@v2
    - name: Docker run
      run: |
        cp ~/app/.env .
        docker-compose up -d --build
